export const PATH = {
    AppDesktop:'/',
    MobileApp:'/HomepageMobileApp',
    Business:'/HomepageBusiness',
    Software:'/HomepageSoftware',
    Eror404:'*',
    AboutUs:'/PageAboutUs',
    BlogArticle:'/PageBlogArticle',
    Careers:'/PageCareers',
    CareersSingle:'/PageCareersSingle',
    CaseStudies:'/PageCaseStudies',
    CaseStudiesSingle:'/PageCaseStudiesSingle',
    ComingSoonCountdown:'/PageComingSoonCountdown',
    ComingSoonSocial:'/PageComingSoonSocial' ,
    ComingSoonSubscribe:'/PageComingSoonSubscribe',
    Contacts:'/PageContacts',
    Legal:'/PageLegal',
    Portfolio:'/PagePortfolio',
    PortfolioSingleCase:'/PagePortfolioSingleCase',
    PricingPlans:'/PagePricingPlans',
    PricingPlansTable:'/PagePricingPlansTable',
    RecoverPassword:'/PageRecoverPassword',
    SignIn:'/PageSignIn',
    SignUp:'/PageSignUp',
} 